### ISSUE TITLE
Extract new Categories, Characteristics and Services

### ISSUE THREAD

**Issue by jlusiardi** [jlusiardi/homekit_python#136]
As discovered in #131 there might be more Categories, Characteristics and Services missing in the non commercial version of the specification. Perhaps they can be extracted via Swift playground on Mac OS.

**Comment by jlusiardi** [comment]
First steps done in branch `fix_136_extract_information`

**Comment by jlusiardi** [comment]
@Jc2k any idea how to get from the UUIDs to the numerical IDs?

**Comment by Jc2k** [comment]
Which numerical ID's? I can only thing of the names and the short uuids?

**Comment by jlusiardi** [comment]
ok, imprecise wording: 
I tried to add some swift playground to extract the missing data for `homekit/model/categories.py` (as to complete table 12-3 page 254 from the spec). Since this was the main issue in #131. Of course we need the UUIDs of the new services for classes in `homekit/model/services` and of the new characteristics for classes in `homekit/model/characteristics` as well.

**Comment by Jc2k** [comment]
Oh i get it - we can see that a new category officially exists because its in the headers but looks like we can't extract the numerical category id, because the const in the header is actually for a UUID. And it looks fairly random, so we can't chop the end off like we do with the other ones.

No - I don't know how to go from UUID to ID, unfortunately.

BTW I just found this which looks useful. Doesn't directly solve the problem, but we might at least be able to manually double check some of this stuff:

https://developer.apple.com/documentation/homekit/testing_your_app_with_the_homekit_accessory_simulator?changes=_5_2
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/HomeKitDeveloperGuide/TestingYourHomeKitApp/TestingYourHomeKitApp.html

**Comment by jlusiardi** [comment]
I am also not into any form of coding in Apple specific languages / frameworks...

**Comment by Jc2k** [comment]
Apple have published a new version of the PDF spec [here](https://developer.apple.com//homekit/specification/). This seems to have new categories and new characteristics (like 00000126-0000-1000-8000-0026BB765291, button event).

**Comment by jlusiardi** [comment]
Yay cool! Thank you! I will have a Look!

**Comment by jlusiardi** [comment]
merged with #169
