### ISSUE TITLE
Possible to retrieve a video frame?

### ISSUE THREAD

**Issue by dmd** [jlusiardi/homekit_python#205]
Is it possible to use this to retrieve a [the current, live] video frame from a Homekit camera?

**Comment by jlusiardi** [comment]
Hello @dmd 
I was working on a branch for that back in spring. So it should be possible after I finalized & merged that one. 
What exactly are you wanting to do? Have script (named e.g. get_image_snapshot.py) to retrieve a single snapshot?

**Comment by dmd** [comment]
Yes, that's precisely it.

**Comment by jlusiardi** [comment]
you might want to have a look for branch `fix_205_get_frame_from_camera` ;)

**Comment by dmd** [comment]
After about an hour of trying to figure out how to get this to work I'm no closer. It's not clear to me how to actually create the pairing data file...

**Comment by Jc2k** [comment]
What did you try? Maybe this will help. It's a documented session with a Koogeek P1EU device. Hopefully it is enough to guide you about the correct order things need to happen in.

https://github.com/jlusiardi/homekit_python/blob/master/doc/tested_devices/Koogeek%20P1EU.md

That should help you get a valid pairing data file at least...

**Comment by dmd** [comment]
I get this:

```
(homekit)
dmd@atto ~$ python3 -m homekit.discover
Name: Circle View 1PF8._hap._tcp.local.
Url: http_impl://192.168.0.199:49152
Configuration number (c#): 3
Feature Flags (ff): Supports HAP Pairing (Flag: 1)
Device ID (id): 2C:25:54:5E:2F:D7
Model Name (md): Circle View Camera
Protocol Version (pv): 1.1
State Number (s#): 73
Status Flags (sf): Accessory has been paired. (Flag: 0)
Category Identifier (ci): IP Camera (Id: 17)

(homekit)
dmd@atto ~$ python3 -m homekit.pair -d 2C:25:54:5E:2F:D7 -p 995-02-008 -f controller.json -a living --log DEBUG
2020-09-21 13:39:35,065 __init__.py:0110 DEBUG #1 ios -> accessory: send SRP start request
2020-09-21 13:39:35,066 __init__.py:0065 DEBUG write message: [
  <6, b'\x01'>,
  <0, b'\x01'>,
]
2020-09-21 13:39:35,232 __init__.py:0072 DEBUG response: [
  <TlvTypes.State, 2>,
  <TlvTypes.Error, 6>,
]
2020-09-21 13:39:35,233 __init__.py:0127 DEBUG #3 ios -> accessory: send SRP verify request
step 3
2020-09-21 13:39:35,233 pair.py:0085 DEBUG step 3
Traceback (most recent call last):
  File "/Users/dmd/venvs/homekit/lib/python3.8/site-packages/homekit-0.18.0-py3.8.egg/homekit/pair.py", line 77, in <module>
  File "/Users/dmd/venvs/homekit/lib/python3.8/site-packages/homekit-0.18.0-py3.8.egg/homekit/controller/controller.py", line 398, in start_pairing
    request, expected = state_machine.send(response)
  File "/Users/dmd/venvs/homekit/lib/python3.8/site-packages/homekit-0.18.0-py3.8.egg/homekit/protocol/__init__.py", line 137, in perform_pair_setup_part1
    error_handler(error.data, 'step 3')
  File "/Users/dmd/venvs/homekit/lib/python3.8/site-packages/homekit-0.18.0-py3.8.egg/homekit/protocol/__init__.py", line 47, in error_handler
    raise UnavailableError(stage)
homekit.exceptions.UnavailableError: step 3
 ```

**Comment by Jc2k** [comment]
Is the device still paired to your iPhone ? Homekit only allows one primary pairing at a time.

**Comment by dmd** [comment]
Oh. Well that's not very useful then :(

**Comment by dmd** [comment]
Not sure I understand this really. I can view the camera on my phone, ipad, and mac -- what is preventing some other client from pulling images too?

**Comment by Jc2k** [comment]
A single pairing is the primary pairing. That pairing can add other sub pairings. There is no way to get your iOS to register home made crypto keys as sub pairings and like wise you can't extract iOS keys to register when homekit_python is the primary.

**Comment by dmd** [comment]
:( oh well. thanks anyway!

**Comment by Jc2k** [comment]
To make this use case work you need a "MITM". I can see how this might work, but all options need some work....

* homekit_python has a [Debug Proxy](https://github.com/jlusiardi/homekit_python/blob/a9fb87bce8ad8495112bd31665068270633ed43f/doc/DebugProxy.md). You pair your camera with homekit_python and then add homekit_python to your phone. homekit_python just forwards the requests to the device, unwrapping and re-wrapping the encryption. It is meant to help debug characteristic read/writes, but in doing so it side steps the limitations I have described. As it is it still impoes the homekit 1-primary-pairing limitation. But if you got stuck into the code you could probably make it so that you can get the image stills you want out of it whilst still having it paired to your phone.

* If your camera has native home assistant support then you can leave it paired to your phone with homekit and use home assistant to get the image snapshots. home assistant does have a native homekit controller and bridge, so you can also use it as a MITM. But it doesn't support camera yet as a controller, only as the bridge.

**Comment by dmd** [comment]
I think this is probably more trouble than it's worth. Thanks anyway.

**Comment by jlusiardi** [comment]
Sorry we could not really help with your request.
Using Apple devices (iPhone, iPad and OS X) and this project in parallel not really possible, because the key sharing happends over the iCloud (at least that's what I am guessing).
