### ISSUE TITLE
AttributeError: 'ThermostatService' object has no attribute 'set_on_set_callback'

### ISSUE THREAD

**Issue by lboue** [jlusiardi/homekit_python#43]
Hello,

I am trying to implement those 3 services on a new demoserver.py version:
1. LightBulbService
2. ThermostatService
3. OutletService

I added a new snippet to expose a thermostat accessory in my [fork repo](https://github.com/lboue/homekit_python/blob/expose_controller_api/demoserver.py
). 
```
        accessory2 = Accessory('thermostat', 'lusiardi.de', 'Demoserver', '0002', '0.1')
        thermostatService = ThermostatService()
        thermostatService.set_on_set_callback(light_switched)
        accessory2.services.append(thermostatService)
        httpd.add_accessory(accessory2)
```

But when I start the script I am get an `'AttributeError: 'ThermostatService' object has no attribute 'set_on_set_callback''` error: 
```
pi@raspberrypi:~/homekit_python $ python3 demoserver.py 
2018-07-10 18:24:19,620 - accessory - INFO - starting
Traceback (most recent call last):
  File "demoserver.py", line 58, in <module>
    thermostatService.set_on_set_callback(light_switched)
AttributeError: 'ThermostatService' object has no attribute 'set_on_set_callback'
```

Could share a callback fonction exemple for thermostatService?

Regards,
Ludovic

**Comment by lboue** [comment]
I managed to do implement my test (https://github.com/lboue/homekit_python/commit/710852bb284da94871c2976a6dde1bcb030d5b28) to get the target temperature/state  
```
=======>  th target temperature: 19.0
=======>  th target temperature: 18.5
=======>  th target temperature: 19.5

=======>  th target state: 0
=======>  th target state: 1
=======>  th target state: 2
=======>  th target state: 3
```


But how can I do to get current temperature/state with somthing like this?
```
thermostatService.set_current_temperature_get_callback(th_current_temperature)
thermostatService.set_current_heating_cooling_state_get_callback(th_current_state)
```
```
2018-07-10 22:02:31,545 - accessory - ERROR - Exception while getting value for 11.24: th_current_state() missing 1 required positional argument: 'new_value'
2018-07-10 22:02:31,547 - accessory - ERROR - Exception while getting value for 11.23: th_current_temperature() missing 1 required positional argument: 'new_value
```

**Comment by jlusiardi** [comment]
Hi,

Ok, forget the deleted first comment. I am not quite sure, what exactly you want to achieve. These callback functions are called if the controller performs a read or write on a characteristic.

E.g. Controller reads the current temperature of the `thermostatService`, the get callback function is invoked (this function has had to be set via `set_current_temperature_get_callback`). 

If the Controller writes the target temperature, the set callback is needed (set via `set_target_temperature_set_callback`).

Joachim

PS: please use only the master branch, since the others are a little experimental. I am trying to include improvements.

PPS: look at https://gist.github.com/jlusiardi/934a098a0cf9940dc4631fccc0384ee3, coded for master and a little simplified.

PPPS: I started working on a Controller  and Accessory Server API but hit some issues. UML diagrams are in https://github.com/jlusiardi/homekit_python/tree/expose_controller_api/doc and I tried to type stuff in the wiki. This does not work yet, but i want to go into that direction.

**Comment by jlusiardi** [comment]
@lboue is this still an issue? ;)
