### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by matyklugDebbuged** [jlusiardi/homekit_python#63]
----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/5y/qt1h5x1140vgy33mjtchxgfc0000gp/T/pip-install-naaa40pq/gmpy2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/5y/qt1h5x1140vgy33mjtchxgfc0000gp/T/pip-record-vrovkgcr/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /private/var/folders/5y/qt1h5x1140vgy33mjtchxgfc0000gp/T/pip-install-naaa40pq/gmpy2/

**Comment by jlusiardi** [comment]
Hi,

i would be very gentle to have some more information in the issue. 

I guess you are using some version of OS X and try to install via pip3? Can you please post more of the installation?

Regards
Joachim

**Comment by matyklugDebbuged** [comment]
macOS Sierra, i installed Python from internet. Yes, using pip3 and pip

**Comment by jlusiardi** [comment]
at least on some linux it works with python 3.7: https://travis-ci.org/jlusiardi/homekit_python/jobs/475953714

can you give the complete command line used with pip and the result?

**Comment by Jc2k** [comment]
This looks like an error building gmpy2 (hard to tell from that error) which can probably be solved by installing 'libmpc' and 'mpfr' frrom brew.

#94 actually removes the need for it, though, and hopefully can be merged soon.

It still won't work on macOS because `py25519` doesn't work on macOS. I will have a PR to migrate to the X25519 key exchange code `cryptography` - at that point it should work on macOS and not need gcc (for http stuff).

**Comment by jlusiardi** [comment]
we removed the assumed culprit (requirement for gmpy2) but got no feedback. I was able to install on OS X high sierra in version 0.12.1 so closing this.
